export const PAGINATION = {
  INITIAL_PAGE: 1,
  PAGE_LIMIT: 10,
  TOTAL_PAGES: 1,
  TOTAL_RECORDS: 0,
  ROWS_PER_PAGE_OPTIONS: [1, 5, 10, 15, 20],
  OPTIONAL_PAGE_LIMIT: 5,
  DROPDOWNS_RECORD_LIMIT: 50,
};
