export const API_ENDPOINTS = {
  SIGNIN: "/auth/signin",
  SIGNUP: "/auth/signup",
  SET_PASSWORD: "/auth/set-password",
  VERIFY_OTP: "/auth/verify-otp",
  VERIFY_TWO_FACTOR_AUTHENTICATION: "/auth/2fa",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  REFRESH_TOKEN: "/auth/refresh-token",
  CHANGE_PASSWORD: "/auth/change-password",
  DASHBOARD_ACTIVITY: "/get-dashboard-data",
  GET_USER_PROFILE: "/users",
  UPDATE_USER_PROFILE: "/users",
  UPDATE_USER_PROFILE_AVATAR: "/users",
  GET_NOTIFICATION: "/notifications",
  GET_UPDATES: "/updates",
  GET_CHANGES: "/get-changes",
  DASHBOARD_USER_ACTIVITY: "/get-dashboard-user-activity",
  GET_PRODUCTS_LOG_LIST: "/products/get-product-log",
  POST_CHANGE_REQUEST: "/add-change",
  UPDATE_CHANGE_REQUEST: "/update-change",
  USERS: "/users",
};
