export const API_TAGS_MAPPED = {
  PRODUCT: "PRODUCT",
  DASHBOARD: "DASHBOARD",
  LOTS: "LOTS",
  ADD_USER_LIST: "ADD_USER_LIST",
};

export const API_TAGS = [
  API_TAGS_MAPPED?.DASHBOARD,
  API_TAGS_MAPPED?.PRODUCT,
  API_TAGS_MAPPED?.LOTS,
  API_TAGS_MAPPED?.ADD_USER_LIST,
];
